version: '3.1'

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$$MYSQL_ROOT_PASSWORD
    volumes: 
      - db:/var/lib/mysql
    #command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.5-php7.4-fpm
    container_name: wordpress
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
      #- /theme/:/var/www/html/wp-
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx
    container_name: webserver
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html
      - ./nginx/:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email admin@company.com --agree-tos --no-eff-email --force-renewal -d domain.com
      
volumes:
  wordpress:
  db:
  letsencrypt:

networks:
  app-network:
    driver: bridge  